### ISSUE TITLE
Error when receiving Geo During Async Multiworld

### ISSUE THREAD

**Issue by Zunawe** [Ijwu/Archipelago.HollowKnight#71] opened 2022-06-12 09:07 UTC
Been playing around with the new release that fixes loading a save (🎉 nice work). Worked fine for just me in my own world, played one game, reloaded twice, no issues. Works mostly fine in a multiworld; even this issue isn't a hindrance.

I've got an OoT world and a HK world going on a local server, and I'm playing both games myself, so they aren't running at the same time. All significant items reached my HK save correctly and the save is working as expected. But when I load HK and it starts listing items that were received while the game was closed in the bottom left corner, sometimes it shows `Error: see ModLog for details.`. Checked the ModLog and there are a few errors that look like this:

```
[ERROR]:[ItemChangerMod] - Error on GiveImmediate for item 26 Geo from Z_OoT:
[ERROR]:[ItemChangerMod] - System.NullReferenceException: Object reference not set to an instance of an object
[ERROR]:[ItemChangerMod] -   at GeoCounter.AddGeo (System.Int32 geo) [0x00000] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[ERROR]:[ItemChangerMod] -   at HeroController.AddGeo (System.Int32 amount) [0x00012] in <2b54cdaf7a934f0eb297d50c4090ea9f>:0 
[ERROR]:[ItemChangerMod] -   at ItemChanger.Items.GeoRockItem.GiveImmediate (ItemChanger.GiveInfo info) [0x00036] in C:\dev\ItemChanger\ItemChanger\Items\GeoRockItem.cs:32 
[ERROR]:[ItemChangerMod] -   at ItemChanger.AbstractItem.Give (ItemChanger.AbstractPlacement placement, ItemChanger.GiveInfo info) [0x00095] in C:\dev\ItemChanger\ItemChanger\AbstractItem.cs:132 
```

All instances of the error are for adding geo. I don't think I actually received the geo either, but I wasn't checking.

I'll pay attention to where the messages appear and whether I get the geo as I keep playing. And let me know if you want any logs.

**Comment by Zunawe** [comment] 2022-06-12 09:11
Probably a dupe of #65. Don't know how I missed that.

It'll be noticed more often now that you can reload the save though I assume.

**Comment by dewiniaid** [comment] 2022-06-12 21:04
Duplicate of #65

**Closed by dewiniaid** 2022-06-12 21:04 UTC
