### ISSUE TITLE
Cannot start game with RandomCharmCosts 

### ISSUE THREAD

**Issue by kaixinqi** [Ijwu/Archipelago.HollowKnight#126] opened 2022-09-05 03:07 UTC
**Describe the bug**
in yaml file, set RandomCharmCosts to random/shuffle, can not start the game.

**To Reproduce**

1. set RandomCharmCosts as random/shuffle(not standard)
2. generate game and click 'start game' in Hollow Knight Archipelago
3. See error

**Expected behavior**
enter the game and fall down at King's Pass

**Screenshots**
err msg in HK mod: An error occurred when attempting to connect...
err msg in server:
```
[websockets.server at 2022-07-23 15:42:33,627]: connection open
[root at 2022-07-23 15:42:34,260]: Notice (all): Paodan (Team #1) playing Hollow Knight has joined. Client(0.3.0), []).
[root at 2022-07-23 15:42:34,261]: Notice (Player Paodan in team 1): Now that you are connected, you can use !help to list commands to run via the server. If your client supports it, you may have additional local commands you can list with /help.
[root at 2022-07-23 15:42:37,325]: Notice (all): Paodan (Team #1) has left the game
[websockets.server at 2022-07-23 15:42:37,325]: connection closed
```
**Additional context**

**Comment by Ijwu** [comment] 2023-02-03 00:07
Cannot reproduce.

Running Archipelago Server v0.3.8 for both generation and hosting.
Running Archipelago.HollowKnight v0.1.1.2 on the client side.

I used the template YAML in a fresh Archipelago installation. I rolled two players, one HK one MC. The HK player's YAML is untouched except for player name and to set `RandomCharmCosts` to `-2` (or `shuffled`).

I was able to connect to the server in the Hollow Knight client as well as receive charms from the server console which showed different charm costs applied.

![image](https://user-images.githubusercontent.com/1393017/216478565-ae02ad3c-b81c-4e15-82a3-2f6174218e97.png)

YAMLs and generation output here:
[AP_74915819806909953969.zip](https://github.com/Ijwu/Archipelago.HollowKnight/files/10574379/AP_74915819806909953969.zip)
[Players.zip](https://github.com/Ijwu/Archipelago.HollowKnight/files/10574380/Players.zip)

---

If you are able to reproduce this issue on current versions and can provide precise reproduction steps as well as player YAMLs you used and the AP.zip file you ended up, that would be most helpful.

Closing for now. You may re-submit or re-open if the issue persists.

**Closed by Ijwu** 2023-02-03 00:07 UTC
Labels: bug, needs investigation
